# docker-compose.yml (coloque na raiz do projeto)
version: '3.8'

services:
  web:
    # Constrói a imagem a partir do Dockerfile que está na pasta 'redbull'
    build: ./redbull

    # Comando para iniciar o servidor Rails, aceitando conexões de fora do contêiner
    command: bin/rails server -b 0.0.0.0

    # Mapeia a porta 3000 do contêiner para a porta 3000 da sua máquina
    ports:
      - "3000:3000"

    # Mapeia a pasta do seu código para dentro do contêiner.
    # Isso permite que alterações no código reflitam instantaneamente, sem precisar reconstruir a imagem.
    volumes:
      - ./redbull:/rails
      # Usa um volume nomeado para manter as gems baixadas (cache), acelerando futuras inicializações.
      - bundle_cache:/usr/local/bundle

# Define um volume reutilizável para o cache das gems
volumes:
  bundle_cache: