services:
  web:
    build: ./redbull

    command: bash -c "rm -f /rails/tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

    ports:
      - "3000:3000"

    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

volumes:
  bundle_cache: